### ISSUE TITLE
Asus UX330CA support

### ISSUE THREAD

**Issue by alexandruioanp** [mishurov/linux_elan1200_touchpad#4]
I'm on Arch Linux. The device ID for my touchpad is 304A. I tried this a few days ago on 4.14 and it seemed to perform much better than the original driver during my limited testing!

Are you meant to blacklist the `hid_multitouch` module? My touchpad only worked if the original driver was loaded first. This would happen on boot and on waking up from sleep.

I've recently updated to kernel 4.15 and the driver no longer seems to work. `modprobe hid-elan` terminates with a SIGKILL, and that seems to mess up everything afterwards (`modprobe hid_multitouch` hangs and I have to reboot).

Thanks a lot for your work on this!

**Comment by mishurov** [comment]
I hold conservative views due to my age according to Churchill and I use the good old Debian. There's no 4.15 kernel in stable backports so I can't give any reasonable comments about the problem.

**Comment by timschroederme** [comment]
I currently use the module on kernel 4.15, working as it should. @alexandruioanp Can you try to compile it again for 4.15?

**Comment by alexandruioanp** [comment]
Thanks for your input, @timschroedernet! I must've been doing something wrong. I recompiled and it works now. However, if I unload the `hid_multitouch` module, I still have the issue of the touchpad not working after waking up the laptop.

**Comment by timschroederme** [comment]
@alexandruioanp I see the same issue after waking up my machine (this is not specific to kernel 4.15, it was always like this). I haven't yet figured out what causes this, seems to be an initialization issue. My current workaround is to use this script with systemd:

```
#!/bin/sh
set -e

if [ "$2" = "suspend" ] || [ "$2" = "hybrid-sleep" ]; then
    case "$1" in
        pre) modprobe -r hid-elan ;;
        post) modprobe hid_multitouch && modprobe -r hid_multitouch && modprobe hid-elan ;;
    esac
fi
```
I have placed this in `/usr/lib64/systemd/system-sleep`, but that might be different for Arch Linux.

**Comment by mishurov** [comment]
Lads, I've fixed the problem. Checkout the latest commit.

**Comment by alexandruioanp** [comment]
@timschroedernet, I tried placing a similar script in several different places in the past, without much luck. @mishurov, that fixed resuming from sleep. I'll try a reboot later. Many thanks!

**Comment by timschroederme** [comment]
Yes, the latest commit fixes the suspend issue. Thanks!

**Comment by alexandruioanp** [comment]
I can confirm that it also works after a reboot.
