### ISSUE TITLE
Commit c386f92 Breaks Functionality

### ISSUE THREAD

**Issue by timschroederme** [mishurov/linux_elan1200_touchpad#5]
The latest commit [c386f92](https://github.com/mishurov/linux_elan1200_touchpad/commit/c386f92d563ab21f8949bda22ddfc8d5b71e472f) fixed the [suspend issue](https://github.com/mishurov/linux_elan1200_touchpad/issues/4) but broke the overall functionality of the module for me. The module is loaded but does not fix anymore the random jumps and random right-click events during two-finger scrolling. I am using kernel 4.15.6.

**Comment by mishurov** [comment]
That's weird, I didn't change anything related directly to event reports. Only initialisation. I added timestamp and hdev constants.

**Comment by mishurov** [comment]
You may try to remove this line
`input_event(td->input, EV_MSC, MSC_TIMESTAMP, td->timestamp + 1);`

And change 
`hdev->quirks |= HID_QUIRK_NO_INPUT_SYNC;`
to
`hdev->quirks |= HID_QUIRK_NO_INIT_REPORTS;`

As it was before the commit. If it helps, I'll make another commit.

**Comment by mishurov** [comment]
I amended the latest commit. I hope it helps.

**Comment by timschroederme** [comment]
Thanks. I think this fixes it for me. Will monitor it for a longer time and re-open if I see it again.
