### ISSUE TITLE
ELAN1200 report structure

### ISSUE THREAD

**Issue by hieplpvip** [mishurov/linux_elan1200_touchpad#9]
Hello @mishurov 

Could you tell me where do you get the structure of ELAN1200 report?

**Comment by mishurov** [comment]
@hieplpvip I'm sorry for ignoring the issue. I'd received the notification when I was very busy and it completely fell out of my mind. If I remember correctly, I used some userspace HID tool which prints the report in hex when I do some physical action with touchpad e.g. moving, tapping, etc. and tried to understand which part of the report corresponds to an action.
